default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: tweetap_development

test:
  <<: *default
  database: tweetap_test

production:
  <<: *default
  database: tweetap_production
  username: tweetap
  password: <%= ENV['TWEETAP_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>